import { Layout } from "@/components/Layout";
import Head from "next/head";
import Image from "next/image";
import ProfilePhoto from "../assets/portfolio.png";
import { AnimatedText } from "@/components/AnimatedText";
import Link from "next/link";
import { LinkArrow } from "@/components/Icons";
import { HireMe } from "@/components/HireMe";
import lightBulb from "../assets/lightBulb.svg";

export default function Home() {
  return (
    <>
      <Head>
        <title>Enes Bek Portfolio</title>
        <meta name="description" content="Generated by myself"></meta>
      </Head>
      <main className="flex items-center text-dark w-full min-h-screen dark:text-light">
        <Layout className="pt-0 md:pt-16 sm:pt-8">
          <div className="flex items-center justify-between w-full lg:flex-col">
            <div className="w-1/2 md:w-full">
              <Image
                src={ProfilePhoto}
                alt="EnesBek"
                className="w-3/4 h-auto lg:hidden md:inline-block md:w-full"
                priority
                sizes="(max-width: 768px) 100vw,
                       (max-width: 1200px) 50vw,
                                           50vw"
              />
            </div>
            <div className="w-1/2 flex flex-col items-center self-center lg:w-full lg:text-center">
              <AnimatedText
                text="Crafting code that's a work of art."
                className="!text-6xl !text-left xl:!text-5xl lg:!text-center lg:!text-6xl md:!text-5xl sm:!text-3xl"
              />
              <p className="my-4 text-base font-medium md:text-small sm:text-xs">
                As an open-source enthusiast and frontend developer, I&apos;m
                passionate about creating beautiful, user-centered designs that
                are powered by the latest front-end technologies. With a focus
                on continuous learning and improvement, I constantly seek to
                enhance my skills and stay up-to-date with the latest trends and
                best practices in the industry.
              </p>
              <div className="flex items-center self-start mt-2 lg:self-center">
                <Link
                  href="/resume.pdf"
                  target="_blank"
                  className="flex items-center bg-dark text-light p-2 px-6 rounded-lg text-lg font-semibold hover:bg-light hover:text-dark border-2 border-solid border-transparent hover:border-dark dark:bg-light dark:text-dark md:p-2 md:px-4 md:text-base"
                  download={true}
                >
                  Resume <LinkArrow className={"w-6 ml-1"} />
                </Link>
                <Link
                  href="mailto:enes.bek.93@gmail.com"
                  target="_blank"
                  className="ml-4 text-lg font-medium capitalize text-dark underline dark:text-light md:text-base"
                >
                  Contact
                </Link>
              </div>
            </div>
          </div>
        </Layout>

        <HireMe />
        <div className="absolute right-8 bottom-8 inline-block w-24 md:hidden">
          <Image src={lightBulb} alt="EnesBek" className="w-full h-auto" />
        </div>
      </main>
    </>
  );
}
