export default function Home() {
  return (
    <>
      <Head>
        <title>Enes Bek Portfolio</title>
        <meta name="description" content="Generated by myself"></meta>
      </Head>
      <main className="flex items-center text-dark w-full min-h-screen">
        <div>Home</div>
      </main>
    </>
  );
}
